name: Generate Algolia serach indicies in JSON & push to Algolia
on:
  push:
    branches: ["main"]
  schedule:
    - cron: '20 * * * *'
jobs:
    algolia:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Generate the content of algolia.json as config
              id: algolia_config
              run: echo "config=$(cat ./crawler-config.json | jq -r tostring)" >> $GITHUB_OUTPUT # crawl off the index content from site
            - name: Push indices to Algolia
              uses: signcl/docsearch-scraper-action@master
              env:
                  APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
                  API_KEY: ${{ secrets.API_KEY }}
                  CONFIG: ${{ steps.algolia_config.outputs.config }}
