name: Bilibili

on:
  # schedule:
    # - cron: '20 * * * *'
  # workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get data from Bilibili
      run: |
        python3 ./pyapp/getVideo.py
    - name: Commit changed data.json file and push changes to repository
      run: |
        git diff
        git config --global user.email "2096358571@qq.com"
        git config --global user.name "mostlai"
        git add -A
        git commit -a -m 'chore(update): update data.json from Bilibili' || exit 0
        git push -f origin main
    - name: Push changes to remote repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAT }} # personal access token
        branch: ${{ github.ref }}
